<?php
//header("Content-Type: application/rss+xml");
require_once('includes/konekcija/baza_konektor.php');
echo "<?xml version='1.0'?>";
echo "<rss version='2.0'>";
echo "<channel>";
echo "<title>".$_SERVER['HTTP_HOST']." RSS Document</title>";
echo "<description>RSS document generated by ".$_SERVER['HTTP_HOST']."</description>";
echo "<link>".$_SERVER['HTTP_HOST']."</link>";
echo "<copyright>Copyright ".$_SERVER['HTTP_HOST']." All Rights Reserved</copyright>";
$konektor = new baza_konektor();
$izlez = $konektor->query("SELECT * FROM vest WHERE objavi='1' ORDER BY ID DESC LIMIT 30");
while($row = $konektor->fetchArray($izlez))
{
	echo "<item>"; 
	echo "<title>".$row['naslov']."</title>";
	echo "<description>".$row['voved']."</description>";
	echo "<link>http://".$_SERVER['HTTP_HOST']."/vest-".$row['id'].".html</link>";
	echo "</item>";
}
echo "</channel>";
echo "</rss>";
?>